version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    volumes:
      - .:/app # Mount the current directory to the container for live code updates
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
